app:
  # Should be the same as backend.baseUrl when using the `app-backend` plugin
  baseUrl: http://localhost:3000

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 80
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      host: ernibackstagepsql.postgres.database.azure.com
      port: 5432
      user: backstage@prodernibackstagepsql
      password: "Dacarma@9211"
      ssl: true
  cache:
    store: memory

auth:
  environment: production
  providers:
    microsoft:
      production:
        clientId: ${{ secrets.AZURE_CLIENT_ID }}
        clientSecret: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenantId: ${{ secrets.AZURE_TENANT_ID }}

techdocs:
  builder: 'external'
  publisher:
    type: 'azureBlobStorage'
    azureBlobStorage:
      containerName: ${{ secrets.TECHDOCS_CONTAINER_NAME }}
      credentials:
        accountName: ${{ secrets.TECHDOCS_STORAGE_ACCOUNT }}
